services:
  quiz_local:
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - API_PORT=80 # default value
    ports:
      - '80:80'
    volumes:
      - ./data:/app/data
